export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const SHOW_USERS_LOADING = 'SHOW_USERS_LOADING';
export const DELETE_USER = 'DELETE_USER';


